# Config example
language = "cpp" # Follow github flavered markdown
compilers = ["/usr/local/bin/g++"] # Compilers for doc test
compiler_options = [
    "-std=c++17",
    "-Wall",
    "-Wextra",
    "-pedantic-errors",
    "-I/opt/boost/boost_1_72_0/include",
    "-I/home/mitama/github/mitama-cpp-result/include",
]
target_link_libraries = [
    "/opt/libfmt/lib/libfmt.so",
]
# A keyword for test code extraction.
# By writing the keywords at the beginning,
# the tool will extract only the code that needs to be tested from all the code blocks.
dogear = "// begin example"
